# Generated by Django 6.0.2 on 2026-06-15 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('normal', 'Normal User'), ('professional', 'Professional User')], default='normal', max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('emp_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
